services:
  api:
    container_name: api  # docker container run --name "api" ${image}
    build: ./api # docker image build "./api"
    ports:
      - 8080:8080 # docker container run -p "8080":"8080"
    tty: true # docker container run -i "-t" ubuntu bash
    volumes:
      - ./api:/workspace:cached # docker container run -v "./api:workspace"
  
  web:
    container_name: web
    build:
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api